#!/usr/bin/env python
import sys
from app import create_app
from flask.cli import FlaskGroup

app = create_app()

with app.app_context():
    cli = FlaskGroup(create_app=create_app)
    cli.main(args=sys.argv[1:] if len(sys.argv) > 1 else ['--help'])
